# https://starship.rs/config/#prompt
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Inserts a blank line between shell prompts
add_newline = true


# A continuation prompt that displays two filled in arrows
continuation_prompt = "‚ñ∂‚ñ∂"


# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character] # The name of the module we are configuring is "character"
success_symbol = "[‚ûú](bold red)" # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false


[git_branch]
symbol = "üå± "
truncation_length = 4
truncation_symbol = ""
